services:
  - type: web
    name: mc-flurry-tiers-api
    env: node
    buildCommand: cd client && npm install && npm run build
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: mc-flurry-tiers-db
          property: connectionString
    plan: free

databases:
  - name: mc-flurry-tiers-db
    databaseName: mc_flurry_tiers
    user: mc_flurry_user
    plan: free
